# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 63a960db3f0a3781bd139d255e1d9d8a26eb7c4db5a7dcca62612183dc8d2e456dd4666adbe64b2eed4b383724118b4951f9d242a58418946476aafcf07034c9

test:
  secret_key_base: 35b1c031a38e7b0a2944b9db9f0dacee5d170f76c4ff7e2c02dee78848ec1b7c398a4777af6b3685d397f8fbdc641f4b5c33cb493d2e871e42feba5997eb7580

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
